QL_USERNetCore/QL_USERNetCore/Controllers/HistoryLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace QL_USERNetCore.Controllers
{
    using X.PagedList;
    using QL_USERNetCore.Models;
    using OfficeOpenXml;
    using System.Data;
    using System.Reflection;
    using ClosedXML.Excel;
    using System.IO;
    using Microsoft.AspNetCore.Http;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Data.SqlClient;

    public class HistoryLoginController : Controller
    {
       
        private readonly DB_USERContext dB_USERContext;

        private readonly IConfiguration _configuration;
        public HistoryLoginController(IConfiguration configuration)
        {
            _configuration = configuration;

        }
        // GET: HistoryLogin
        public ActionResult Index(int? page)
        {
            ViewBag.Session = HttpContext.Session.GetString("Code");
            if (ViewBag.Session == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var n = HttpContext.Session.GetString("Code").ToString();

                // 1. Tham số int? dùng để thể hiện null và kiểu int
                // page có thể có giá trị là     và kiểu int.

                // 2. Nếu page = null thì đặt lại là 1.
                if (page == null) page = 1;


                string ConnectionString = _configuration.GetConnectionString("DBConnectString");
                SqlConnection connection = new SqlConnection(ConnectionString);
                connection.Open();
                string SqlQuery = "exec GetHistory";
                SqlCommand command = connection.CreateCommand();
                command.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataAdapter da = new SqlDataAdapter(SqlQuery, connection);
                DataTable dataTable = new DataTable();

                int link = da.Fill(dataTable);

                List<HistoryLogin> HistoryList = new List<HistoryLogin>();

                for (int i = 0; i < dataTable.Rows.Count; i++)
                {
                    HistoryLogin history = new HistoryLogin();
                    history.Id = Convert.ToInt32(dataTable.Rows[i]["ID"]);
                    history.Code = dataTable.Rows[i]["Code"].ToString();
                    history.LoginDate = dataTable.Rows[i]["LoginDate"].ToString();
                    history.LogoutDate = dataTable.Rows[i]["LogoutDate"].ToString();
                    HistoryList.Add(history);
                }
                int pageSize = 10;

                var links = HistoryList.ToPagedList(page ?? 1, pageSize);


                // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
                // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
                int pageNumber = (page ?? 1);

                // 5. Trả về các Link được phân trang theo kích thước và số trang.
                return View(links.ToPagedList(pageNumber, pageSize));
            }

        }
        public ActionResult DisplayHistoy()
        {
            var n = HttpContext.Session.GetString("Code").ToString();
            //var n = Session["Code"];
            //var user = db.Users.ToList();
            var HistoryRecords = dB_USERContext.HistoryLogin.Where(p => p.Code == n).ToList();
            return View("Index", HistoryRecords);
        }
    }
}

QL_USERNetCore/QL_USERNetCore/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace QL_USERNetCore.Controllers
{
    using X.PagedList;
    using QL_USERNetCore.Models;
    using OfficeOpenXml;
    using System.Data;
    using System.Reflection;
    using ClosedXML.Excel;
    using System.IO;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.Data.SqlClient;
    using System.Configuration;
    using Microsoft.VisualBasic;
    using DocumentFormat.OpenXml.Math;
    using DocumentFormat.OpenXml.InkML;
    using DocumentFormat.OpenXml.ExtendedProperties;
    using DocumentFormat.OpenXml.Spreadsheet;

    //[Authorize]
    public class UserController : Controller
    {
        private readonly DB_USERContext dB_USERContext;
        private readonly IConfiguration _configuration;
        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;

        }
        public IActionResult Index(int? page)
        {
            ViewBag.Session = HttpContext.Session.GetString("Code");
            if (ViewBag.Session == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ExportExcel();

                if (page == null) page = 1;

             
                //-----------------------------get data ---------------------------
                string ConnectionString = _configuration.GetConnectionString("DBConnectString");
                SqlConnection connection = new SqlConnection(ConnectionString);
                connection.Open();
                string SqlQuery = "exec GetUser";
                SqlCommand command = connection.CreateCommand();
                command.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataAdapter da = new SqlDataAdapter(SqlQuery, connection);
                DataTable dataTable = new DataTable();

                int link = da.Fill(dataTable);
                // DataTable to List
                List<User> UserList = new List<User>();
                for (int i = 0; i < dataTable.Rows.Count; i++)
                {
                    User user = new User();
                    user.Id = Convert.ToInt32(dataTable.Rows[i]["Id"]);
                    user.Code = dataTable.Rows[i]["Code"].ToString();
                    user.Name = dataTable.Rows[i]["Name"].ToString();
                    user.Password = dataTable.Rows[i]["Password"].ToString();
                    user.InsertUserId = dataTable.Rows[i]["InsertUserId"].ToString();
                    user.InsertDate = dataTable.Rows[i]["InsertDate"].ToString();
                    user.LastEditUser = dataTable.Rows[i]["LastEditUser"].ToString();
                    user.LastEditDate = dataTable.Rows[i]["LastEditDate"].ToString();
                    UserList.Add(user);
                }
                int pageSize = 10;

                var links = UserList.ToPagedList(page ?? 1, pageSize);

                int pageNumber = (page ?? 1);

                return View(links.ToPagedList(pageNumber, pageSize));
            }
        }


        public IActionResult CreateUser(QL_USERNetCore.Models.User model)
        {
            ViewBag.Session = HttpContext.Session.GetString("Code");
            if (ViewBag.Session == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                if (model.Code == null || model.Password == null)
                {
                    ViewBag.CreateUserErro = "Code và Password không được bỏ trống!";
                    return View("CreateUser", model);
                }
                else
                {
                    string ConnectionString = _configuration.GetConnectionString("DBConnectString");
                    SqlConnection connection = new SqlConnection(ConnectionString);
                    connection.Open();
                    SqlCommand cmd2 = connection.CreateCommand();
                    cmd2.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd2.CommandText = "TimUserCode";
                    cmd2.Parameters.AddWithValue("@Code", model.Code);
                    int UserRecord = Convert.ToInt32(cmd2.ExecuteScalar());
                    connection.Close();
                    if (UserRecord == 0)
                    {
                        connection.Open();
                        SqlCommand cmd3 = connection.CreateCommand();
                        cmd3.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd3.CommandText = "inser_user";
                        cmd3.Parameters.AddWithValue("@Code", model.Code);
                        cmd3.Parameters.AddWithValue("@Name", model.Name);
                        cmd3.Parameters.AddWithValue("@Password", model.Password);
                        cmd3.Parameters.AddWithValue("@InsertUserId", HttpContext.Session.GetString("Code"));
                        cmd3.Parameters.AddWithValue("@InsertDate", DateTime.Now.ToString());

                        cmd3.ExecuteScalar();
                        TempData["CreateUserError"] = "Thêm thành công!";
                        return View("CreateUser", model);
                    }
                    else
                    {
                        TempData["CreateUserError"] = "Code đã được sử dụng vui lòng chọn Code khác!";
                        return View("CreateUser", model);
                    }
                    var r = "";

                    //var InsertDate = DateTime.Now.ToString();
                    //var InsertUserId = HttpContext.Session.GetString("Code");
                    //dB_USERContext.User.Add(new User() { Code = model.Code, Name = model.Name, Password = model.Password, InsertUserId = InsertUserId, InsertDate = InsertDate });
                    //dB_USERContext.SaveChanges();
                    //ViewBag.CreateUser = "Thêm tài khoản thành công!";
                    //TempData["CreateUser"] = "Thêm tài khoản thành công!";
                    return View("CreateUser", model);
                }
            }
        }


        public IActionResult EditUser(int idUser)
        {
            ViewBag.Session = HttpContext.Session.GetString("Code");
            if (ViewBag.Session == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                string ConnectionString = _configuration.GetConnectionString("DBConnectString");
                SqlConnection connection = new SqlConnection(ConnectionString);
                SqlCommand command = connection.CreateCommand();

                connection.Open();
                string SqlQuery = "exec GetDataEdit @ID";

                command.CommandType = System.Data.CommandType.StoredProcedure;

                SqlDataAdapter da = new SqlDataAdapter(SqlQuery, connection);
                da.SelectCommand.Parameters.AddWithValue("@ID", Convert.ToInt32(idUser));
                DataTable dataTable = new DataTable();

                int UserDetail = da.Fill(dataTable);

                var user = new User();
                for (int i = 0; i < dataTable.Rows.Count; i++)
                {

                    user.Id = Convert.ToInt32(dataTable.Rows[i]["Id"]);
                    user.Code = dataTable.Rows[i]["Code"].ToString();
                    user.Name = dataTable.Rows[i]["Name"].ToString();
                    user.Password = dataTable.Rows[i]["Password"].ToString();
                    user.LastEditUser = dataTable.Rows[i]["LastEditUser"].ToString();
                    user.LastEditDate = dataTable.Rows[i]["LastEditDate"].ToString();
                }
                return View("EditUser", user);
            }
        }

        [HttpPost]
        public IActionResult EditUser(User user)
        {
            ViewBag.Session = HttpContext.Session.GetString("Code");
            if (ViewBag.Session == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                string ConnectionString = _configuration.GetConnectionString("DBConnectString");
                SqlConnection connection = new SqlConnection(ConnectionString);
                connection.Open();
                SqlCommand cmd = connection.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "TimUser";
                cmd.Parameters.AddWithValue("@ID", user.Id);
                int UserRecord = Convert.ToInt32(cmd.ExecuteScalar());
                connection.Close();
                if (UserRecord == 1)
                {
                    connection.Open();
                    SqlCommand cmd1 = connection.CreateCommand();

                    cmd1.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd1.CommandText = "EditUser";
                    cmd1.Parameters.AddWithValue("@ID", Convert.ToInt32(user.Id));
                    cmd1.Parameters.AddWithValue("@Code", user.Code);
                    cmd1.Parameters.AddWithValue("@Name", user.Name);
                    cmd1.Parameters.AddWithValue("@Password", user.Password);
                    cmd1.Parameters.AddWithValue("@LastEditUser", HttpContext.Session.GetString("Code"));
                    cmd1.Parameters.AddWithValue("@LastEditDate", DateTime.Now.ToString());
                    cmd1.ExecuteScalar();
                    connection.Close();
                    TempData["EditMessage"] = "Sửa thành công! " + user.Code;
                    //var UserRecords = dB_USERContext.User.ToList();
                    return View("EditUser", user);
                }
                else

QL_USERNetCore/QL_USERNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QL_USERNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" href="~/../CSSJS/Style.css" />*@

   

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QL_USERNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreateUser">ADD USER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User Details</a>
                         </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HistoryLogin" asp-action="Index">History Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ImportExcel" asp-action="index">Import Excel</a>
                            </li>
                        @if (ViewBag.Session == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">LOGIN</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">LOGOUT</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="">Xin chào: @ViewBag.Session</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">


        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - QL_USERNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/../CSSJS/Script.js" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>